### PR TITLE
Migration

### PR DESCRIPTION
**Pull request by zenith-noble01**

### CODE REVIEW

**Comment by zenith-noble01** [comment]
it's now okay
merge then

**Review by JosiasAurel — APPROVED** [review]
Nice one

**Comment by JosiasAurel** [comment]
This was better. Please also make sure to name your pull requests so it will be easier in the future. You could name this one as 
`Add menu to home page` -> Which will make it clear of the changes you have made

**Comment by zenith-noble01** [comment]
copy that 1/1

**Comment by zenith-noble01** [comment]
but how where do we put the global style 
And how do we make it  functional because if you run it you'll find the default margin and padding of the browser

**Pull request merged**
